### ISSUE TITLE
Request to restore older demo collection

### ISSUE THREAD

**Issue by shrikrishnaholla** [huggingface/transformers.js-examples#18]
In the older documentation of transformers.js, there used to be a demo playground, where you could select between several usecases, zero-shot classification, QA etc

It's still there as "A collection of demos" in https://huggingface.co/docs/transformers.js/index

Could we restore that demo? Because it had lots of examples that could be run on cpu as well. I don't see it listed in the README in the newer repo

Context: https://www.reddit.com/r/LocalLLaMA/comments/1h9r3lv/tts_webgpu_the_first_ever_texttospeech_web_app/m17wcog/?context=3

**Comment by xenova** [comment]
It's technically still up: https://huggingface.github.io/transformers.js/, but certainly needs a revamp! cc @cfahlgren1 😇

**Comment by shrikrishnaholla** [comment]
Yup, that is what I was looking for! :raised_hands: 

Closing this now
